
PUBLISHED_STATUS_DRAFT = 1
PUBLISHED_STATUS_PUBLISHED = 2
PUBLISHED_STATUS_ARCHIVED = 3

PUBLISHED_STATUS_CHOICES = (
    (PUBLISHED_STATUS_DRAFT, 'draft'),
    (PUBLISHED_STATUS_PUBLISHED, 'published'),
    (PUBLISHED_STATUS_ARCHIVED, 'archived'),
)
