# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:26
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    def load_data(apps, schema_editor):
        call_command("loaddata", "apps/articles/fixtures/initial.json")

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='published_status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'draft'), (2, b'published'), (3, b'archived')], default=1),
        ),
        migrations.RunPython(load_data),
    ]

